# Generated by Django 4.2.7 on 2025-09-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardAuthorities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('authority_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'award_authorities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExcursionMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('excursion_id', models.BigIntegerField()),
                ('media_type', models.CharField(max_length=255)),
                ('media_url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('display_order', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'excursion_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Excursions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('long_description', models.TextField()),
                ('google_location_pin', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_hours', models.IntegerField()),
                ('max_participants', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'excursions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('icon_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'icons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'members_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('propertyid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('longdescription', models.TextField()),
                ('shortdescription', models.CharField(max_length=255)),
                ('propertycategory', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('districtid', models.IntegerField()),
                ('defaultpictureid', models.CharField(max_length=20)),
                ('googlemappin', models.CharField(max_length=200)),
                ('verified', models.CharField(max_length=3)),
                ('verifiedby', models.CharField(max_length=200)),
                ('verifiedtimestamp', models.CharField(max_length=200)),
                ('verifiednotes', models.CharField(max_length=200)),
                ('enabled', models.CharField(max_length=3)),
                ('nextverification', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyAwards',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('property_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('year_awarded', models.IntegerField()),
                ('url', models.URLField()),
                ('award_authority_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'property_awards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('icon_id', models.BigIntegerField()),
                ('picture', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'property_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyFacilities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('property_id', models.BigIntegerField()),
                ('icon_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_picture_id', models.BigIntegerField()),
                ('long_description_details', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'property_facilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyPictures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('property_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('picture_url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_cover', models.BooleanField()),
                ('display_order', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'property_pictures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyRestrictions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('property_id', models.BigIntegerField()),
                ('restriction_id', models.BigIntegerField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'property_restrictions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyRoomCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('property_id', models.BigIntegerField()),
                ('verified', models.BooleanField()),
                ('verification', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
                ('size_details', models.CharField(max_length=255)),
                ('max_occupancy', models.IntegerField()),
                ('no_of_units', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'property_room_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyRoomCategoryFeatures',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_category_id', models.BigIntegerField()),
                ('icon_id', models.BigIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'property_room_category_features',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restrictions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'restrictions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('config_key', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('config_value', models.TextField()),
                ('data_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'system_configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subject', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Teachers',
                'db_table': 'teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('updated_at', models.DateTimeField()),
                ('last_login_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSessions',
            fields=[
                ('session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'user_sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('property_id', models.BigIntegerField()),
                ('verified', models.BooleanField()),
                ('verified_notes', models.TextField()),
                ('verifier_timestamp', models.DateTimeField()),
                ('times_verified', models.IntegerField()),
                ('next_verification_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'verification_details',
                'managed': False,
            },
        ),
    ]
