# Generated by Django 4.2.7 on 2025-09-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_bookings_and_registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='property',
        ),
    ]
