# Generated by Django 4.2.7 on 2025-09-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_bookings_and_registrations', '0002_alter_property_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='districts',
            table='district',
        ),
    ]
