# Generated by Django 4.2.7 on 2025-09-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_bookings_and_registrations', '0003_alter_districts_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_price_details',
            fields=[
                ('property_price_details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guest_price', models.BigIntegerField()),
                ('minimum_night_price', models.BigIntegerField()),
            ],
            options={
                'db_table': 'property_price_details',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='propertycategories',
            table='propertycategory',
        ),
        migrations.AlterModelTable(
            name='propertyfacilities',
            table='propertyfacilities',
        ),
    ]
