# Generated by Django 4.2.7 on 2025-09-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_bookings_and_registrations', '0004_property_price_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPriceDetails',
            fields=[
                ('property_price_details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guest_price', models.BigIntegerField()),
                ('minimum_night_price', models.BigIntegerField()),
            ],
            options={
                'db_table': 'property_price_details',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='property_price_details',
        ),
    ]
